test: Migrate CI to GitHub Actions [SDK-4455]
auth0/password-sheriff pull request #34
Opened 2023-09-15 08:12 UTC by evansims

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

This pull request replaces our current CircleCI continuous integration suite for auth0-react with a new workflow using GitHub Actions.

### References

Please see internal ticket SDK-4455.

### Testing

This pull request replaces our continuous integration suite with one built in GitHub's native Actions ecosystem. It aligns with other migrations taking place across our repositories.

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not the default branch

2023-09-18 12:43 UTC, frederikprijck requested changes

2023-09-18 12:43 UTC, frederikprijck commented on .github/workflows/publish.yml
> +          cache: npm
We should set the registry-url to npm here, else it wont use authentication. See:

- https://github.com/actions/setup-node/blob/main/src/main.ts#L59-L61
- https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

We encountered this with lock and fixed it: https://github.com/auth0/lock/pull/2445

```suggestion
          cache: npm
          registry-url: 'https://registry.npmjs.org/'
```

2023-09-18 16:32 UTC, evansims commented
@frederikprijck Fixed, thanks

2023-09-21 09:40 UTC, frederikprijck approved these changes

2023-09-21 14:08 UTC, merged